---
- name: Install and Configure MariaDB for MajiTask v3.0
  hosts: localhost
  become: true
  vars:
    db_name: "majitask"
    db_user: "majitask"
    db_password: "majitask_secure_2024!"
    mariadb_root_password: "3070"
    
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install MariaDB and dependencies
      apt:
        name:
          - mariadb-server
          - mariadb-client
          - python3-pymysql
          - acl
        state: present

    - name: Ensure MariaDB service is running and enabled
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB installation (set root password)
      mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
      ignore_errors: yes

    - name: Remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Disallow root login remotely
      mysql_user:
        name: root
        host: "{{ ansible_hostname }}"
        state: absent
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Create MajiTask database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Create MajiTask database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Configure MariaDB for better performance
      lineinfile:
        path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter | default(omit) }}"
      loop:
        - { regexp: "^#?bind-address", line: "bind-address = 127.0.0.1" }
        - { regexp: "^#?max_connections", line: "max_connections = 200", insertafter: "^bind-address" }
        - { regexp: "^#?innodb_buffer_pool_size", line: "innodb_buffer_pool_size = 256M", insertafter: "^max_connections" }
        - { regexp: "^#?query_cache_size", line: "query_cache_size = 16M", insertafter: "^innodb_buffer_pool_size" }
        - { regexp: "^#?query_cache_limit", line: "query_cache_limit = 1M", insertafter: "^query_cache_size" }
      notify: restart mariadb

    - name: Create backup directory for MariaDB
      file:
        path: "/backup/mariadb"
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'

    - name: Create MariaDB backup script
      copy:
        dest: "/usr/local/bin/backup-mariadb.sh"
        content: |
          #!/bin/bash
          
          # MariaDB backup script for MajiTask
          DATE=$(date +%Y%m%d_%H%M%S)
          BACKUP_DIR="/backup/mariadb"
          DB_NAME="{{ db_name }}"
          DB_USER="root"
          DB_PASSWORD="{{ mariadb_root_password }}"
          
          # Create backup
          mysqldump -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" > "$BACKUP_DIR/majitask_backup_$DATE.sql"
          
          # Compress backup
          gzip "$BACKUP_DIR/majitask_backup_$DATE.sql"
          
          # Keep only last 7 days of backups
          find "$BACKUP_DIR" -name "majitask_backup_*.sql.gz" -mtime +7 -delete
          
          echo "Backup completed: majitask_backup_$DATE.sql.gz"
        mode: '0755'
        owner: root
        group: root

    - name: Add MariaDB backup to crontab
      cron:
        name: "MariaDB MajiTask backup"
        minute: "0"
        hour: "2"
        job: "/usr/local/bin/backup-mariadb.sh"
        user: root

    - name: Configure MariaDB log rotation
      copy:
        dest: "/etc/logrotate.d/mariadb"
        content: |
          /var/log/mysql/*.log {
            daily
            missingok
            rotate 52
            compress
            delaycompress
            notifempty
            create 644 mysql mysql
            postrotate
              if test -x /usr/bin/mysqladmin && \
                /usr/bin/mysqladmin ping &>/dev/null
              then
                /usr/bin/mysqladmin flush-logs
              fi
            endscript
          }
        mode: '0644'
        owner: root
        group: root

    - name: Display MariaDB setup information
      debug:
        msg: |
          MariaDB setup completed successfully!
          
          Database: {{ db_name }}
          User: {{ db_user }}
          Password: {{ db_password }}
          Root Password: {{ mariadb_root_password }}
          
          Connection details for application:
          - Host: localhost
          - Port: 3306
          - Database: {{ db_name }}
          - Username: {{ db_user }}
          
          Backup script installed at: /usr/local/bin/backup-mariadb.sh
          Daily backups scheduled at 2:00 AM

  handlers:
    - name: restart mariadb
      systemd:
        name: mariadb
        state: restarted
