---
- hosts: "localhost"
  become: true
  become_user: root
  vars:
    nginx_site_filename: "majitask.conf"
    majitask_domain: "app.majitask.fun"  # Your domain
    app_path: "/home/apps/majitask"  # Your app path
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: latest
      notify:
        - restart nginx

    - name: Copy Majitask NGINX configuration to sites-available
      copy:
        dest: "/etc/nginx/sites-available/{{ nginx_site_filename }}"
        content: |
          server {
              listen 80;
              server_name {{ majitask_domain }};

              root {{ app_path }}/dist;
              index index.html;

              # Security headers
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-XSS-Protection "1; mode=block" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header Referrer-Policy "strict-origin-when-cross-origin" always;

              # Serve React app (SPA routing)
              location / {
                  try_files $uri $uri/ /index.html;
              }

              # Proxy API requests to Node.js backend
              location /api/ {
                  proxy_pass http://localhost:3001;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              # Static assets caching
              location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg)$ {
                  expires 1y;
                  add_header Cache-Control "public, immutable";
                  log_not_found off;
              }

              # Deny access to sensitive files
              location ~ /\. {
                  deny all;
              }

              # Deny access to Node.js files
              location ~ \.(json|md|env)$ {
                  deny all;
              }
          }
        owner: root
        group: root
        mode: "0644"

    - name: Enable Majitask NGINX site
      file:
        src: "/etc/nginx/sites-available/{{ nginx_site_filename }}"
        dest: "/etc/nginx/sites-enabled/{{ nginx_site_filename }}"
        state: link

    - name: Remove default NGINX site (if exists)
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
