---
- name: Configure UFW firewall rules
  hosts: localhost
  become: true
  tasks:
    - name: Allow incoming services
      ufw:
        rule: allow
        name: "{{ item }}"
      loop:
        - OpenSSH

    - name: Allow incoming ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '80'
        - '443'

    # ufw supports connection rate limiting, which is useful for protecting
    # against brute-force login attacks. ufw will deny connections if an IP
    # address has attempted to initiate 6 or more connections in the last
    # 30 seconds. See  http://www.debian-administration.org/articles/187
    # for details. Typical usage is:
    - name: Limit incoming SSH connections
      ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Allow all outgoing connections
      ufw:
        rule: allow
        direction: out

    - name: Deny all other incoming connections
      ufw:
        rule: deny
        direction: in

    - name: Enable UFW
      ufw:
        state: enabled
