---
- hosts: localhost
  connection: local
  vars:
    users:
      - "majid"
  tasks:
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: admin
        state: present
        gid: 99
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "admin,www-data"
        shell: /bin/bash
        skeleton: /etc/skel
      with_items: "{{ users }}"
    - name: Add authorized keys
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/keys/'+ item + '.key.pub') }}"
      loop: "{{ users }}"
    - name: Allow admin users to sudo without a password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%admin"
        line: "%admin ALL=(ALL) NOPASSWD: ALL"
