---
- name: Deploy backup script and crontab jobs for MajiTask_v1 server maintenance
  hosts: localhost
  become: true
  vars:
    backup_base_dir: "/var/backups/majitask_v1"
    log_dir: "/var/log"
    app_path: "/home/apps/majitask_v1/majitask"
    
  tasks:
    - name: Create backup directory structure
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /root/bin
        - "{{ backup_base_dir }}"
        - "{{ backup_base_dir }}/app"
        - "{{ backup_base_dir }}/database"
        - "{{ backup_base_dir }}/uploads"
        - "{{ backup_base_dir }}/logs"
        - "{{ log_dir }}"

    - name: Deploy enhanced backup script to /root/bin/server_backup.sh
      copy:
        src: "files/server/server_backup.sh"
        dest: "/root/bin/server_backup.sh"
        owner: root
        group: root
        mode: '0755'
      notify: test_backup_script
    
    - name: Deploy production crontab job file for server tasks
      copy:
        src: "files/server/crontab"
        dest: "/etc/cron.d/majitask_v1_maintenance"
        owner: root
        group: root
        mode: '0644'
      notify: restart_cron

    - name: Create backup log file
      file:
        path: "/var/log/majitask_v1_backup.log"
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Create health check log file
      file:
        path: "/var/log/majitask_v1_health.log"
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Install required packages for backup operations
      package:
        name: "{{ item }}"
        state: present
      loop:
        - gzip
        - tar
        - mailutils
        - mysql-client
        - logrotate

    - name: Configure logrotate for MajiTask_v1 logs
      copy:
        dest: "/etc/logrotate.d/majitask_v1"
        content: |
          {{ app_path }}/logs/*.log {
              daily
              missingok
              rotate 30
              compress
              delaycompress
              notifempty
              sharedscripts
              postrotate
                  systemctl reload majitask_v1 2>/dev/null || true
              endscript
          }
          
          /var/log/majitask_v1_*.log {
              daily
              missingok
              rotate 30
              compress
              delaycompress
              notifempty
          }
        owner: root
        group: root
        mode: '0644'

    - name: Test database connectivity
      shell: |
        mysql -h127.0.0.1 -umajitask_v1 -pmajitask_secure_2024! -e "SELECT 1" majitask_v1
      register: db_test
      ignore_errors: yes
      no_log: true

    - name: Display database connectivity status
      debug:
        msg: |
          Database connectivity: {{ 'SUCCESS' if db_test.rc == 0 else 'FAILED' }}
          {% if db_test.rc != 0 %}
          Error: {{ db_test.stderr | default('Unknown error') }}
          {% endif %}

  handlers:
    - name: test_backup_script
      shell: |
        echo "Testing backup script syntax..."
        bash -n /root/bin/server_backup.sh
      register: syntax_check
      failed_when: syntax_check.rc != 0

    - name: restart_cron
      service:
        name: cron
        state: restarted
